name: Common Workflow

on:
  workflow_call:
    inputs:
      dev_secret:
        type: string
      common_secret:
        type: string

jobs:
  common-sample:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    steps:
      - name: echo in commmon workflow
        run: |
          echo "input dev_secret: ${{  inputs.dev_secret }}"
          echo "input common_secret: ${{ inputs.common_secret }}"
          echo "org_secret: ${{ secrets.ORG_SECRET }}"


      - name: Call echo.yml with secret value as argument
        uses: ./echo.yml
        with:
          dev_secret: ${{ inputs.dev_secret }}
          common_secret: ${{ inputs.common_secret }}
          org_secret: ${{ secrets.ORG_SECRET }}

