name: Echo Workflow

on:
  workflow_call:
    inputs:
      dev_secret:
        type: string
      common_secret:
        type: string
      org_secret:
        type: string

jobs:
  echo:
    runs-on: ubuntu-latest

    steps:
      - name: Echo input value
        run: |
        echo "dev_secret: ${{ inputs.dev_secret }}"
        echo "common_secret: ${{ inputs.common_secret }}"
        echo "org_secret: ${{ inputs.org_secret }}"
